In [1]:
import torch
import numpy as np
import time

In [2]:
a = torch.rand(10000, 10000, device='cuda')
a2 = torch.rand(10000, 10000, device='cpu')
b = np.random.rand(10000, 10000)


In [3]:
%%time
a = torch.tensor(b, device='cuda')
torch.linalg.inv(a).cpu().numpy()

CPU times: user 870 ms, sys: 477 ms, total: 1.35 s
Wall time: 1.35 s


array([[ 0.25627082,  0.04348943,  0.25903434, ...,  0.42798268,
         0.46126544,  0.12095826],
       [ 0.02173229, -0.08006999, -0.11801647, ..., -0.08608952,
        -0.10047093, -0.12842557],
       [-0.1384585 , -0.01489644, -0.07793175, ..., -0.20786375,
        -0.20459139, -0.04526983],
       ...,
       [-0.06706845, -0.11328807, -0.2095444 , ..., -0.24249662,
        -0.22705313, -0.18602278],
       [ 0.04298783, -0.0200986 , -0.00142172, ...,  0.03770989,
         0.05909944, -0.04011615],
       [-0.16916276,  0.0074047 , -0.10090859, ..., -0.21114173,
        -0.22168052,  0.01343903]])

In [4]:
%%time
a2 = torch.tensor(b, device='cpu')
torch.linalg.inv(a2).numpy()

CPU times: user 1min 26s, sys: 6.12 s, total: 1min 32s
Wall time: 4.19 s


array([[ 0.25627082,  0.04348943,  0.25903434, ...,  0.42798268,
         0.46126544,  0.12095826],
       [ 0.02173229, -0.08006999, -0.11801647, ..., -0.08608952,
        -0.10047093, -0.12842557],
       [-0.1384585 , -0.01489644, -0.07793175, ..., -0.20786375,
        -0.20459139, -0.04526983],
       ...,
       [-0.06706845, -0.11328807, -0.2095444 , ..., -0.24249662,
        -0.22705313, -0.18602278],
       [ 0.04298783, -0.0200986 , -0.00142172, ...,  0.03770989,
         0.05909944, -0.04011615],
       [-0.16916276,  0.0074047 , -0.10090859, ..., -0.21114173,
        -0.22168052,  0.01343903]])

In [5]:
%%time
np.linalg.inv(b)

CPU times: user 2min 20s, sys: 8.74 s, total: 2min 29s
Wall time: 6.36 s


array([[ 0.25627082,  0.04348943,  0.25903434, ...,  0.42798268,
         0.46126544,  0.12095826],
       [ 0.02173229, -0.08006999, -0.11801647, ..., -0.08608952,
        -0.10047093, -0.12842557],
       [-0.1384585 , -0.01489644, -0.07793175, ..., -0.20786375,
        -0.20459139, -0.04526983],
       ...,
       [-0.06706845, -0.11328807, -0.2095444 , ..., -0.24249662,
        -0.22705313, -0.18602278],
       [ 0.04298783, -0.0200986 , -0.00142172, ...,  0.03770989,
         0.05909944, -0.04011615],
       [-0.16916276,  0.0074047 , -0.10090859, ..., -0.21114173,
        -0.22168052,  0.01343903]])